#  飞书
APP_ID: cli_a4abb457fd9ad013 
APP_SECRET: y3ZThmXy9iXUXjv7C9ZrTeXemsVdrU7D
APP_ENCRYPT_KEY: PDskBWQWPQ5dZCpTPKKmPcrWeWxyqUZx
APP_VERIFICATION_TOKEN: PDskBWQWPQ5dZCpTPKKmPcrWeWxyqUZx 
# 请确保和飞书应用管理平台中的设置一致
BOT_NAME: ChatGPT 
# openAI key 支持负载均衡 可以填写多个key 用逗号分隔
OPENAI_KEY: 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 
# 服务器配置
HTTP_PORT: 9000
HTTPS_PORT: 9001
USE_HTTPS: false
CERT_FILE: cert.pem
KEY_FILE: key.pem
# openai 地址, 一般不需要修改, 除非你有自己的反向代理
API_URL: https://api.openai.com
# 代理设置, 例如 "http://127.0.0.1:7890", ""代表不使用代理
HTTP_PROXY: ""
